name: Build borealis demo

on:
  push:
  pull_request:
jobs:
  switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    strategy:
      fail-fast: false
      matrix:
        driver: [ glfw, sdl2, deko3d ]
        include:
          - { driver: glfw, cmake: "-DUSE_GLFW=ON", ext: "gl3-glfw" }
          - { driver: sdl2, cmake: "-DUSE_SDL2=ON", ext: "gl3-sdl2" }
          - { driver: deko3d, cmake: "-DUSE_DEKO3D=ON", ext: "deko3d" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_SWITCH=ON ${{ matrix.cmake }}
          make -C build borealis_demo.nro -j$(nproc)
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-switch-${{ matrix.ext }}
          path: build/borealis_demo.nro

    name: linux (${{ matrix.driver }}${{ matrix.ext }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { driver: gl2, cmake: "-DUSE_GL2=ON" }
          - { driver: gles2, cmake: "-DUSE_GLES2=ON" }
          - { driver: gles3, cmake: "-DUSE_GLES3=ON" }
          - { driver: gl3, cmake: "-DUSE_GLFW=ON", ext: "-glfw" }
          - { driver: gl3, cmake: "-DUSE_SDL2=ON", ext: "-sdl2" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends libdbus-1-dev libxkbcommon-dev \
            libwayland-dev wayland-protocols xorg-dev
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake }} \
              -DPLATFORM_DESKTOP=ON \
              -DUSE_LIBROMFS=ON
          make -C build -j$(nproc)
          output_dir=borealis-linux-x86_64-${{ matrix.driver }}${{ matrix.ext }}
          strip build/borealis_demo
          mkdir -p ${output_dir}
          mv build/borealis_demo ${output_dir}
          tar -czvf ${output_dir}.tar.gz ${output_dir}
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-linux-x86_64-${{ matrix.driver }}${{ matrix.ext }}
          path: borealis-linux-x86_64-${{ matrix.driver }}${{ matrix.ext }}.tar.gz