name: Build New-mGBA for Switch

on:
  push:
  pull_request:
jobs:
  macos:
    runs-on: macos-14
    name: macos (${{ matrix.window.name }})
    strategy:
      matrix:
        window:
          - { name: glfw, cmake: "-DUSE_GLFW=ON" }
          - { name: sdl2, cmake: "-DUSE_SDL2=ON" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_DESKTOP=ON -DBUNDLE_MACOS_APP=ON ${{ matrix.window.cmake }}
          make -C build -j$(sysctl -n hw.ncpu)
          mkdir borealis-macos-${{ matrix.window.name }}
          mv build/borealis_demo.app borealis-macos-${{ matrix.window.name }}/
          tar -czvf borealis-macos-${{ matrix.window.name }}.tar.gz borealis-macos-${{ matrix.window.name }}
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-macos-${{ matrix.window.name }}
          path: borealis-macos-${{ matrix.window.name }}.tar.gz
  switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    strategy:
      fail-fast: false
      matrix:
        driver: [ glfw, sdl2, deko3d ]
        include:
          - { driver: glfw, cmake: "-DUSE_GLFW=ON", ext: "gl3-glfw" }
          - { driver: sdl2, cmake: "-DUSE_SDL2=ON", ext: "gl3-sdl2" }
          - { driver: deko3d, cmake: "-DUSE_DEKO3D=ON", ext: "deko3d" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_SWITCH=ON ${{ matrix.cmake }}
          make -C build New_mGBA.nro -j$(nproc)
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-switch-${{ matrix.ext }}
          path: build/New_mGBA.nro