name: Build New_mGBA for Switch

on:
  push:
  pull_request:
jobs:
  macos:
    runs-on: macos-14
    name: macos (${{ matrix.window.name }})
    strategy:
      matrix:
        window:
          - { name: glfw, cmake: "-DUSE_GLFW=ON" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_DESKTOP=ON -DBUNDLE_MACOS_APP=ON ${{ matrix.window.cmake }}
          make -C build -j$(sysctl -n hw.ncpu)
          mkdir New_mGBA-macos-${{ matrix.window.name }}
          mv build/New_mGBA.app New_mGBA-macos-${{ matrix.window.name }}/
          tar -czvf New_mGBA-macos-${{ matrix.window.name }}.tar.gz New_mGBA-macos-${{ matrix.window.name }}
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: New_mGBA-macos-${{ matrix.window.name }}
          path: New_mGBA-macos-${{ matrix.window.name }}.tar.gz
  switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    strategy:
      fail-fast: false
      matrix:
        driver: [ glfw ]
        include:
          - { driver: glfw, cmake: "-DUSE_GLFW=ON", ext: "gl3-glfw" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_SWITCH=ON ${{ matrix.cmake }}
          make -C build New_mGBA.nro -j$(nproc)
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-switch-${{ matrix.ext }}
          path: build/New_mGBA.nro