name: Build New-mGBA for Switch

on:
  push:
  pull_request:
jobs:
  ios:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: cache
        id: cache-key
        run: echo "IOS_CACHE_KEY=ios-cmake-build-dir-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '.github/workflows/ci.yaml') }}" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v4
        id: ios-cache
        with:
          path: build
          key: ${{ steps.cache-key.outputs.IOS_CACHE_KEY }}
      - name: Build
        run: |
          ./build_libromfs_generator.sh
          cmake -B build -G Xcode -DPLATFORM_IOS=ON -DPLATFORM=OS64 -DDEPLOYMENT_TARGET=13.0
          cmake --build build
          ditto -ck --rsrc --sequesterRsrc --keepParent build/Debug-iphoneos/borealis_demo.app borealis_demo.zip
      - uses: actions/cache/save@v4
        if: ${{ !steps.ios-cache.outputs.cache-hit }}
        with:
          path: build
          key: ${{ steps.cache-key.outputs.IOS_CACHE_KEY }}
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-ios
          path: borealis_demo.zip
  switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    strategy:
      fail-fast: false
      matrix:
        driver: [ glfw, sdl2, deko3d ]
        include:
          - { driver: glfw, cmake: "-DUSE_GLFW=ON", ext: "gl3-glfw" }
          - { driver: sdl2, cmake: "-DUSE_SDL2=ON", ext: "gl3-sdl2" }
          - { driver: deko3d, cmake: "-DUSE_DEKO3D=ON", ext: "deko3d" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM_SWITCH=ON ${{ matrix.cmake }}
          make -C build New_mGBA.nro -j$(nproc)
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-switch-${{ matrix.ext }}
          path: build/New_mGBA.nro